### PR TITLE
Added index.html

### PR DESCRIPTION
**Pull request by varGeneric**
I am literally a html god.

### CODE REVIEW

**Comment by frankye8998** [comment]
*an

**Comment by GeorgeShao** [comment]
:O

**Comment by ColtonMak** [comment]
Obsolete btw
[The Marquee element (Obsolete)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee)
> uses obsolete feature
> html god btw

**Comment by varGeneric** [comment]
> obsolete

You misspelled legendary

```
Make it obsolete in favor of CSS but define its expected behavior, for backward compatibility.
```

Not like it's going anywhere, nothing is more permanent than backwards compatibility.       

Besides, would CSS work in IE2? I didn't think so.

**Comment by ColtonMak** [comment]
True, I see your point

**Pull request merged**
